### ISSUE TITLE
footnotes are broken for some posts

### ISSUE THREAD

**Issue by dawneraq** [jlengstorf/lengstorf.com#116]
# Description

Hey Jason! I've found myself in the Gatsby community recently while learning React. After catching glimpses of your raised eyebrow and bald head both on Twitter _and_ among the Gatsby contributors, I decided to check out [learnwithjason.dev](http://learnwithjason.dev) and your blog. Super inspiring stuff! Between your videos and writing about modern JavaScript tools, design, working (freelance) remotely, and sensible productivity strategies, I'm hooked.

One thing I noticed is that the footnotes for some of your blog posts have been pulled out of the popup `<aside>`. Do you think the problem lies within `useFootnotes` in the `gatsby-theme-jason-blog` plugin, `gatsby-remark-numbered-footnotes`, or elsewhere?

# Screenshots

## Working

The footnote appears as expected.

![image](https://user-images.githubusercontent.com/9038965/81980815-25f33780-95e4-11ea-9bd2-9868eb81f5fa.png)

## Not working, Exhibit A

Footnote text is missing from the popup box, and appears as a paragraph where it's defined:

![image](https://user-images.githubusercontent.com/9038965/81980872-40c5ac00-95e4-11ea-90ed-952ffb8ae8bf.png)

## Not working, Exhibit B

Footnote text is missing from popup box...

![image](https://user-images.githubusercontent.com/9038965/81981008-808c9380-95e4-11ea-91c0-b131b7b6b269.png)

Only to appear as paragraphs at the bottom of the page.

![image](https://user-images.githubusercontent.com/9038965/81981042-91d5a000-95e4-11ea-8e2f-f5dd121906d6.png)

**Comment by jlengstorf** [comment]
ah, crap. I think I know what this is, and it’s a _really_ annoying whitespace parsing issue 😔

I’ll try my suspected fix out and see if it works
