### ISSUE TITLE
Blog posts page links

### ISSUE THREAD

**Issue by frontendwizard** [jlengstorf/lengstorf.com#120]
When you go to the blog post pages and click on older links, the app goes to `https://lengstorf.com/blog//2/`, which leads to a blank page. There's an extra `/` after blog. Probably something is off on the link generation logic.

**Comment by jlengstorf** [comment]
thanks for the heads up! I think you're right. the problem is most likely in `gatsby-theme-jason-blog` — I'll try to get it fixed ASAP
