### ISSUE TITLE
Important notice from Amplitude: please update to v4.1.1 or newer

### ISSUE THREAD

**Issue by ryanashcraft** [jlengstorf/lengstorf.com#43]
Amplitude is encouraging all of our customers using our JavaScript SDK < v4.1.1 to update immediately in order to avoid possible data contamination. We plan to stop collecting data from older versions of the SDK in early 2019. For more context, please see this [article](https://amplitude.zendesk.com/hc/en-us/articles/360019036051-11-1-2018-Pre-v-4-1-1-JS-SDK-Deprecation).

This project seems to be currently using v3.4.0. Please update to the latest SDK version v4.5.0.

**Comment by jlengstorf** [comment]
@ryanashcraft The new instructions seem to leave out the way to add an API key. It says to replace `API_KEY`, but there's no instance of `API_KEY` in the sample code.

Any ideas?

**Comment by jlengstorf** [comment]
Referring to https://amplitude.zendesk.com/hc/en-us/articles/115001361248#installation

**Comment by jlengstorf** [comment]
@ryanashcraft Actually, do you have a tutorial or an example installation using the npm package? The docs are super unclear on how to use it.

**Comment by ryanashcraft** [comment]
@jlengstorf Yeah that zendesk snippet is confusing. Check out https://developers.amplitude.com/#installation – it's a newer, developer-friendly resource we built.

You have the API key here: https://github.com/jlengstorf/lengstorf.com/blob/115166e667bb3e1ec4dfb06baeb5aead843edbfb/plugins/gatsby-plugin-amplitude/gatsby-ssr.js#L41. You shouldn't need to update that bit.

If you're using webpack you can create a module alias: `amplitude: path.resolve('./node_modules/amplitude-js/amplitude.js'),` Then you can `import amplitude from `amplitude;`. I'm not sure exactly how to do that with Gatsby.

I also made a plugin specifically for Gatsby 2.0 if you're interested: https://github.com/ryanashcraft/gatsby-plugin-amplitude-analytics

**Comment by jlengstorf** [comment]
@ryanashcraft Sweet! I switched over to your plugin; will get that committed up soon.

I also opened a PR to add a perf boost. https://github.com/ryanashcraft/gatsby-plugin-amplitude-analytics/pull/3

Thanks for the nudge on this!
