### ISSUE TITLE
How is "isBlogPost" being used?

### ISSUE THREAD

**Issue by cachemoney** [jlengstorf/lengstorf.com#65]
Hi there,
Can you elaborate how this variable is used? I see that it determines what schema.org template is used in your SEO module, but in your POST template, it doesnt seem to be set at all.  Am I missing something?
Thanks!

**Comment by jlengstorf** [comment]
@cachemoney It's a boolean flag that lets the SEO component know that it should add extra fields, so it just gets set as an attribute directly: https://github.com/jlengstorf/lengstorf.com/blob/6a7a07d38adc1187493a8296f052e808901f4469/src/templates/post.js#L117-L121

Does that make sense?
