### ISSUE TITLE
tweetable comes up undefined

### ISSUE THREAD

**Issue by jlengstorf** [jlengstorf/lengstorf.com#69]
Looks like the URL is undefined: https://twitter.com/fquednau/status/1087750356094906368

This makes sense, now that I'm thinking about it, because the `location` probably doesn't exist during the build. For now the fix is probably just to hard-code the base URL and grab the slug from GraphQL.

**Comment by AbhimanyuAryan** [comment]
@jlengstorf can you discuss the approach? Or this is fixed?

**Comment by jlengstorf** [comment]
Whoops! This was fixed in https://github.com/jlengstorf/gatsby-theme-jason-blog/commit/eaf83d8f416a1cb460d6a88af97ee129d2eda615
