### ISSUE TITLE
Trailing slash SEO issue

### ISSUE THREAD

**Issue by nickreese** [jlengstorf/lengstorf.com#70]
Hey man, love the site. Was looking for a Gatsby site that was open source and public so I could see how Gatsby did from an SEO perspective. 

In my audit of your site and a few others, I found 2 reoccurring themes:

- Linking to the non-trailing slash version, resulting in 301 redirects between pages. e.g. https://lengstorf.com/not-a-phony to https://lengstorf.com/not-a-phony/
- Tags, categories, and paginated archives, don't have unique title tags. 

Here is a crawl of your site for your records. :) https://www.dropbox.com/s/sdzwzdtbhvn5fvk/lengstorf.csv?dl=0

Ping me with any questions. Overall, I think Gatsby may be a workable long term solution. :)

**Comment by isakib** [comment]
Hi @nickreese , 
I've seeing the report, it shows that http://prntscr.com/mds78i that  **two years in airbnbs** is non-indexable but it shows in google http://prntscr.com/mdsa8k (as indexed) 
Can you clarify this.

**Comment by nickreese** [comment]
You nailed the issue:

Across the site there are links to: http://lengstorf.com/two-years-in-airbnbs which in turn redirects to http://lengstorf.com/two-years-in-airbnbs/. These are technically two different URLs. All links throughout the content should include the trailing slash.

http://lengstorf.com/two-years-in-airbnbs is not index-able. :) But, http://lengstorf.com/two-years-in-airbnbs/ is.

**Comment by isakib** [comment]
@nickreese, Thanks. I understand now 👍 
Hope @jlengstorf will take care of that issue.

**Comment by jlengstorf** [comment]
GitHub's formatting is not helping me understand this. 😅 

So the solution to this, if I'm understanding correctly, is to do a find-and-replace on my site for all links to e.g. `href="/two-years-in-airbnbs"` and replace them with `href="/two-years-in-airbnbs/"`?

Or is there something additional here?

In addition, I need to add title tags for the categories/tags pages.

Anything else I need to fix to correct this?

**Comment by nickreese** [comment]
@jlengstorf Correct, but on all URLs. Basically if an internal link is going to be created and it doesn't contain the trailing slash... add one for consistency.

**Comment by jlengstorf** [comment]
@nickreese sounds good. Thanks!

**Comment by jlengstorf** [comment]
To the best of my knowledge this has been corrected. Please let me know if there‘s something I‘ve missed!
