### ISSUE TITLE
graphql error while building 

### ISSUE THREAD

**Issue by AbhimanyuAryan** [jlengstorf/lengstorf.com#75]
```
lengstorf.com git:(master) ✗ gatsby build
success open and validate gatsby-configs — 0.086 s
success load plugins — 0.798 s
success onPreInit — 6.064 s
success delete html and css files from previous builds — 0.012 s
success initialize cache — 0.015 s
success copy gatsby files — 0.152 s
success onPreBootstrap — 0.076 s
⠄ source and transform nodes
API key is required to connect to Airtable
warning The gatsby-source-airtable plugin has generated no Gatsby nodes. Do you need it?
success source and transform nodes — 31.764 s
success building schema — 1.235 s
success createPages — 1.103 s
success createPagesStatefully — 0.551 s
success onPreExtractQueries — 0.027 s
success update schema — 0.414 s
error GraphQL Error There was an error while compiling your site's GraphQL queries.
  Error: RelayParser: Encountered 1 error(s):
- Unknown field 'allAirtable' on type 'Query'. Source: document `usersSoalDesktopBlogsLengstorfComSrcComponentsSpeakingEventsJs2707283071` file: `GraphQL request`

  GraphQL request (3:9)
  2:       {
  3:         allAirtable(filter: { table: { eq: "Events" } }) {
             ^
  4:           totalCount

```

**Comment by jlengstorf** [comment]
@AbhimanyuAryan my site builds using Airtable data, which requires an API key. If you build a new site using `gatsby-theme-jason-blog`, it should be my site without content or custom stuff like the Airtable integration.

Alternatively, you could set up an Airtable with these two tables:
- https://airtable.com/shragvnFckZYeUhvm/tblQwat4f9t7DJuVD?blocks=hide
- https://airtable.com/shr5IvPfIuL0PpKZo/tblhIXOm5nCO6jq4Z?blocks=hide

And update the `gatsby-source-airtable` config to match your setup.

Note that you'll need Algolia keys as well (or disable that plugin as well). See https://github.com/jlengstorf/lengstorf.com/blob/master/.env.EXAMPLE for details.

I'm going to close this, but please let me know if you have additional questions!

**Comment by AbhimanyuAryan** [comment]
Can you remove airtable and algolia. It looks like they are paid especially airtable?

**Comment by AbhimanyuAryan** [comment]
Also, why are you using Airtable? To store blog data in cloud table(database)? Can you explain it a bit? Will the blog still work we remove Airtable?

**Comment by AbhimanyuAryan** [comment]
Ok, I think I'll need more help from you. Since I have never used Airtable before

* Created an Airtable account. Created a workspace `Blog`. Then I went to project tracker to create Tables
![Screen Shot 2019-03-13 at 12 09 07 PM](https://user-images.githubusercontent.com/8083613/54258591-19f78a00-4589-11e9-9e95-103ec3252af4.png)

* Created two tables. Imported data from your tables 

1. Events

![Screen Shot 2019-03-13 at 12 31 12 PM](https://user-images.githubusercontent.com/8083613/54259492-f2ee8780-458b-11e9-90a8-5980dcc22ad9.png)

2. Talks

![Screen Shot 2019-03-13 at 12 30 52 PM](https://user-images.githubusercontent.com/8083613/54259504-fd108600-458b-11e9-9cfa-25138ce650a9.png)

and then I created sharable links for them
![Screen Shot 2019-03-13 at 12 31 02 PM](https://user-images.githubusercontent.com/8083613/54259531-1580a080-458c-11e9-8430-83fd95097d1d.png)

after adding API key in `.env`
AIRTABLE_API_KEY="keysadfasdfasdf"

I changed gatsby-config.js

```
   {
      resolve: 'gatsby-source-airtable',
      options: {
        apiKey: process.env.AIRTABLE_API_KEY,
        tables: [
          {
            // Base: https://airtable.com/shrtR5ICGdbntCsT5
            baseId: 'shrtR5ICGdbntCsT5',
            tableName: 'Events',
            tableView: 'Accepted',
            tableLinks: ['Accepted_Talk(s)'],
          },
          {
            // Base: https://airtable.com/shrKRJ0W2D16Q1hVp
            baseId: 'shrKRJ0W2D16Q1hVp',
            tableName: 'Talks',
            tableView: 'Grid view',
          }
        ]
      }
    }
```

but when I do `gatsby build`. I get this error

```
error Plugin gatsby-source-airtable returned an error

  Error: Could not find what you are looking for
```

What do you mean bgy tableLinks: ['Accepted_Talk(s)']. I have kept it same. All I did was to name my tables `Events` and `Talks` 

For `Events` and `Talks` I choose these tabs and renamed them too

![Screen Shot 2019-03-13 at 12 36 04 PM](https://user-images.githubusercontent.com/8083613/54259671-993a8d00-458c-11e9-94fa-574015173ae8.png)

**Comment by jlengstorf** [comment]
No problem!

So, in Airtable, you can create "views", which are filtered or otherwise customized data views. In my `Events` table, I've created a view called `Accepted` that only shows me events where I've been accepted to speak.

That's what the `tableView` option is specifying. So you'll need to create that view or change it to match the name of your view.

The `tableLinks` field maps the `Accepted Talk(s)` column in the `Events` table to the data in the `Talks` table, which allows me to make nested queries (e.g. event => talk details).

You've already got the Accepted Talk(s) column, so if you update the view names to match your table it should work.

**Comment by AbhimanyuAryan** [comment]
Updated the view names

<img width="895" alt="Screenshot 2019-03-15 at 2 18 19 AM" src="https://user-images.githubusercontent.com/8083613/54390506-a65c9680-46c8-11e9-98a4-7c10cd996251.png">
<img width="832" alt="Screenshot 2019-03-15 at 2 18 24 AM" src="https://user-images.githubusercontent.com/8083613/54390507-a65c9680-46c8-11e9-8b7c-42ce1e6ace97.png">

I get this error
```
error Plugin gatsby-source-airtable returned an error


  Error: Could not find what you are looking for


(sharp:7192): GLib-CRITICAL **: 02:19:24.954: g_hash_table_lookup: assertion 'hash_table != NULL' failed
gatsby build  46.94s user 3.69s system 153% cpu 33.080 total
```

<img width="685" alt="Screenshot 2019-03-15 at 2 20 11 AM" src="https://user-images.githubusercontent.com/8083613/54390623-ffc4c580-46c8-11e9-9ca3-8d738f8851df.png">
<img width="683" alt="Screenshot 2019-03-15 at 2 20 37 AM" src="https://user-images.githubusercontent.com/8083613/54390624-005d5c00-46c9-11e9-8d6b-f49a9e87b020.png">

**Comment by jlengstorf** [comment]
@AbhimanyuAryan try removing the `tableLinks` option and see if it starts up. At this point, without seeing the code, there’s not much more that I can do. My approach to debugging this would be to disable things one at a time until I find the thing that’s breaking, then figure out why that thing is breaking.

Good luck!

**Comment by AbhimanyuAryan** [comment]
@jlengstorf here's to repo

https://github.com/ivdstudios/abhimanyuaryan.github.io

**Comment by jlengstorf** [comment]
@AbhimanyuAryan I looked at the repo, but a lot of things are missing (content, images, etc.) that cause problems for the build. At this point, I'd strongly encourage you to start with a simpler starter project. Unfortunately, I'm not able to do any further debugging on this one.

Check the docs for the Airtable source plugin — they're thorough and will walk you through setting up your own Airtable integration: https://github.com/jbolda/gatsby-source-airtable

Good luck!

**Comment by AbhimanyuAryan** [comment]
@jlengstorf but can you not add everything to your git repo. So, if I clone & fix airtable + algolia. It should just work?

**Comment by AbhimanyuAryan** [comment]
I couldn't find a better mdx starter. This is the only good mdx starter

**Comment by jlengstorf** [comment]
@AbhimanyuAryan if you delete the Airtable stuff and the speaking page, you won't need to worry about it at all.

There are [MDX starters](https://www.gatsbyjs.org/starters/?c=MDX&v=2) that are much simpler to get up and running — my site isn't really a starter; it's just my site. 😅 

Good luck!
