### ISSUE TITLE
Content: Very small typo in the article 'Level setting'

### ISSUE THREAD

**Issue by k-sav** [jlengstorf/lengstorf.com#89]
>If you’ve already _through_ through the vision and strategy, don’t try to convince yourself to start over when things get hard. Instead, CTFD and JFDI.

**Comment by jlengstorf** [comment]
Whoops. I’ll get a fix pushed soon unless someone beats me to it with a PR. 😄 

Thanks!

**Comment by k-sav** [comment]
No probs. For some crazy reason I thought the content was coming from elsewhere (airtable?), otherwise I would have just PR'd it myself 😆
